### ISSUE TITLE
Influxdb v2

### ISSUE THREAD

**Issue by madasus** [alsuren/mijia-homie#182]
Hello,

I'm struggling getting this connected to influxdb2 (which uses a token and not user/pass).  Can anyone help with the correct syntax?

[influxdb]
# The URL of the InfluxDB to which to connect.
url="http://localhost:8086"
# The username with which to authenticate to InfluxDB, if any.
#username=""
# The password with which to authenticate to InfluxDB, if any.
#password=""

**Comment by madasus** [comment]
https://community.influxdata.com/t/unable-to-connect-v1-clients-to-influxdbv2/21630/5

**Comment by qwandor** [comment]
I'm glad you figured it out! I haven't tried InfluxDB 2 yet myself, so I'm not familiar with how it differs. It looks like the InfluxDB client library we use has a [method](https://docs.rs/influx_db_client/0.5.0/influx_db_client/client/struct.Client.html#method.set_jwt_token) to set a JWT rather than username and password, so if that would be useful to support somehow let me know (or feel free to send a PR).

**Comment by xanderificnl** [comment]
To make it work w/ influxdb v2 you can also do this:

```bash
# create v1 compatible authentication user/password and grant write access to a bucket.
influx v1 auth create --org ORG_NAME --username USERNAME --password PASSWORD --write-bucket BUCKET_ID

# configure homie-influx
[influxdb]
url = "http://172.16.32.2:8086/write"
username = "USERNAME"
password = "PASSWORD"
```

( tested w/ InfluxDB v2.4.0 )
